version: 0.2

phases:
  install:
    commands:
      - echo "Install phase"
      - npm ci
  build:
    commands:
      - echo "Build phase"
      - npm run test
      - npm run build
      - ls -la dist # Debugging: List contents of dist
artifacts:
    files:
      - '**/*'
    name: BuildOutput
    base-directory: dist
  