version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm install -g aws-cdk
  build:
    commands:
      - npm run build
      - ls -la
      - cdk deploy $API_STACK_NAME --app "npx ts-node --prefer-ts-exts ./stack/app.ts" --require-approval never